{
    "home": "Main",
    "template_screen": "Template",
    "home_screen": "Homepage",
    "choose_language": "Choose Language",
    "skip": "Skip",
    "first": "Brand New Mobile Banking App",
    "second": "Easy Banking Operations",
    "third": "Kartvelian languages",
    "page_readable_content1": "A modern, easy to navigate and convenient mobile banking application for your daily purposes",
    "page_readable_content2": "Here, you will make all banking operations instantly. We believe that the new concept of contacts and easily navigable functional capabilities will make you satisfied",
    "page_readable_content3": "We especially appreciate everything Georgian, accordingly, Mingrelian and Svan languages are added to the application",
    "otp_enter_code": "Please enter otp",
    "sent_on_number": "Which was sent on number",
    "resend_text_countdown": "send the code again in case non-delivery",
    "otp_in": "in",
    "change_language": "Change Language",
    "save_username": "Save user",
    "name": "Name",
    "password": "Password",
    "forgot_password": "Forgot password",
    "login": "Login",
    "registration": "Sign up",
    "next": "Next",
    "i_agree": "Agree to the",
    "terms_and_conditions": "terms and conditions",
    "terms_and_conditions_2": "Terms and Conditions",
    "finish": "Finish",
    "personal_info": "Personal information",
    "pn": "ID number",
    "birthDate": "Date of birth",
    "phone_number": "Phone number",
    "username": "Username",
    "month_0": "January",
    "month_1": "February",
    "month_2": "March",
    "month_3": "April",
    "month_4": "May",
    "month_5": "June",
    "month_6": "July",
    "month_7": "August",
    "month_8": "September",
    "month_9": "October",
    "month_10": "November",
    "month_11": "December",
    "unblock": "Unblock",
    "user_is_blocked": "User is blocked",
    "unblock_press_button": "Press unblock for unblocking",
    "invalid_sms_code": "Sms code is invalid.",
    "did_not_receive_code": "Did not receive SMS code?",
    "wrong_username_or_password": "Provided data is incorrect",
    "incognito_user": "Incognito user",
    "back": "Back",
    "restore_password": "Password restore",
    "login_with_faceid_or_passcode": "Log in via Face ID or Passcode",
    "forgot_passcode": "Forgot Password?",
    "activate": "Activate",
    "create_passcode_for_login": "Create passcode for easy log in",
    "want_to_set_faceid": "Want to set Face ID?",
    "want_to_set_fingerprint": "Want to set the fingerprint authorization?",
    "you_dont_have_local_auth": "You do not have set the simple authorization",
    "simple_login_ready": "Simple log in",
    "close": "Close",
    "settings": "Settings",
    "edit_from_settings": "You can edit from settings",
    "simple_login": "Simple login",
    "do_you_want_simple_login": "Do you want to activate simple log in",
    "passcode": "passcode",
    "faceid": "Face ID",
    "fingerprint": "fingerprint",
    "confirm_pincode": "please confirm passcode",
    "incorrect_pin_code": "Data is incorrect",
    "more": "More",
    "exchange_rates": "Exchange rates",
    "locations": "Locations",
    "contact": "Contact",
    "privacy": "Privacy",
    "my_money": "My funds",
    "todays_expenses": "Spent today",
    "my_points": "My points",
    "upcoming_payments": "Upcoming Payments",
    "offers": "Offers",
    "latest_transactions": "Latest Transactions",
    "blocked": "Blocked",
    "transactions": "Transactions",
    "date_filter": "Filter by date",
    "from": "From",
    "to": "To",
    "choose": "Choose",
    "clear": "Clear",
    "start_date_must_be_less_than_end_date": "Starting date must be less than end date",
    "found_results": "{{count}} result(s) found",
    "filter": "Filter",
    "share": "Share",
    "template": "Template",
    "details": "Details",
    "account_name": "Account Name",
    "account": "Account",
    "gel": "GEL",
    "gel": "{{price}} GEL",
    "usd": "USD",
    "return_back": "Back",
    "products": "Products",
    "new": "New",
    "accounts_and_cards": "Accounts and Cards",
    "deposits": "Deposits",
    "loans_and_installments": "Loans and Installments",
    "approved_loan": "Your loan is approved!",
    "instalment_card": "Installment Card",
    "approved": "Approved",
    "unused": "Unused",
    "request_new": "Request New",
    "schedule": "Schedule",
    "history": "History",
    "name2": "Name",
    "base": "Base",
    "percent": "Percent",
    "commission": "Commission",
    "offset": "Offset",
    "left_to_pay": "Left to pay",
    "upcoming": "upcoming",
    "payed": "Paid",
    "edit_name": "Edit the name",
    "you_dont_have_products": "You don't have any products in Mobile Bank",
    "request_product": "Request product",
    "request_card": "Request Card",
    "create_deposit": "Create Dposit",
    "request_loan": "Request Loan",
    "request_installment": "Request Installment",
    "block_card_confirm": "Please confirm blocking of the card",
    "block": "Block",
    "cancel": "cancel",
    "installments": "installments",
    "total_activated_installment": "total active installment base",
    "insurance": "Insurance",
    "monthly_payment": "Monthly payment",
    "remaining_payments": "Remaining Payments",
    "installment_account": "Installment account",
    "copy": "Copy",
    "account_copied_successfully": "Account has been copied successfully",
    "deposit_account": "Deposit Account",
    "currency": "Currency",
    "interest_accrual": "Accrued Interest",
    "deposit_percent": "Deposit Percent",
    "open_date": "Open date",
    "expiration_date": "Expiration Date",
    "contract_number": "Contract Number",
    "interest_violation": "In case of Interest violation",
    "deposit_violation": "Deposit breach",
    "add_or_transfer": "add of transfer",
    "share_account": "Share account",
    "block_card": "Block card",
    "pay_transfer": "Pay transfer",
    "show_on_homepage": "Show on homepage",
    "card_class": "Card class",
    "card_number": "Card Number",
    "card_valid_date": "Card valid thru",
    "account_type": "Account Type",
    "annual_percent_rate": "Annual percent rate",
    "card_details": "Card Details",
    "account_details": "Account details",
    "all": "All",
    "search": "Search",
    "rates": "Rates",
    "official_rate": "Official Rate",
    "buy": "Buy",
    "sell": "Sell",
    "last_30_days": "Last 30 days",
    "calculator": "Calculator",
    "where": "To",
    "mobile_bank_rate": "Mobile bank rate",
    "today": "Today",
    "enable_location": "Enable Location",
    "enable_location_desc": "Please enable location to let us show you the interesting destinations",
    "enable": "Enable",
    "km": "Km",
    "m": "M",
    "service_centers": "Service Centers",
    "service_center": "Service Center",
    "atm": "ATM",
    "atms": "ATMs",
    "near_you": "Near you",
    "choose_city": "Choose city",
    "open": "Open",
    "closed": "closed",
    "services": "Services",
    "city": "City",
    "search_city": "Find City",
    "Near_me": "Near me",
    "georgia": "Georgia",
    "search_service_centers": "Search ATM or Service Center",
    "strong": "Strong",
    "medium": "Medium",
    "weak": "Weak",
    "password_min_length": "Minnimum 8 Symbols",
    "password_with_uppercase": "Minnimum 1 Uppercase",
    "password_with_digit": "Minnimum 1 digit",
    "item_details": "Item details",
    "item": "Item",
    "item_price": "Item price",
    "installment_details": "Installment details",
    "activation_date": "Activation date",
    "activated_amount": "Used amount",
    "amount_left_to_pay": "Amount left to pay",
    "installment_expiration_date": "Installment expiration date",
    "lari": "GEL",
    "dollar": "USD",
    "ruble": "RUR",
    "pound": "GBP",
    "euro": "EUR",
    "registration_completed_successfully": "Registration completed",
    "user_unblocked_successfully": "User unblocked successfully!",
    "wrong_pincode": "Provided data is incorrect",
    "invalid_forgot_password_data": "Invalid ID number or date of birth",
    "password_restored_successfully": "Password restored Successfully!",
    "mon-fri": "Monday-Friday",
    "pay_mobile": "Mobile TopUp",
    "name_or_number": "Name or Number",
    "number": "Number",
    "contacts": "Contacts",
    "amount_to_pay": "Amount To Pay",
    "choose_service": "Select Service",
    "saturday": "Saturday",
    "enter_search_term": "Enter Search Keyword",
    "income": "Income",
    "expense": "Expense",
    "money_in_out": "Money in/out",
    "total_liabilities": "Total Liabilities",
    "mobile_payment": "Mobile TopUp",
    "payments": "Payments",
    "transfer": "Transfers",
    "cmts_withdrawal": "Remitances",
    "select_currency": "Select Currency",
    "select_account": "Select Account",
    "where_choose_account": "Where(Select Account)",
    "receiver_account": "Receiver Account",
    "receiver_name": "Account Name",
    "amount": "Amount",
    "to_other_account": "To someone else's Account",
    "transfer_description": "Description",
    "pay": "Pay",
    "enter_passcode_to_confirm": "Enter Passcode To Confirm",
    "confirm": "Confirm",
    "including_fee": "Fee",
    "something_happened": "Error occurred",
    "found": "Found",
    "results": "Result",
    "future_payments": "Payments",
    "add_contact": "Add Contact",
    "edit_contact": "Edit Contact",
    "phone_numbers": "Phone Number",
    "add_number": "Add Number",
    "add_account": "Add Account",
    "accounts": "Accounts",
    "full_name": "Full Name",
    "account_number": "Account Number",
    "save": "Save",
    "delete": "Delete",
    "transfers": "Transfers",
    "to_own_account": "Own Accounts",
    "to_another_account": "To someone else's account",
    "send": "Transfer",
    "electricity": "Electricity",
    "water": "Water",
    "natural_gas": "Natural GAS",
    "cleaning": "Cleaning",
    "television": "Television",
    "internet": "Internet",
    "templates": "Templates",
    "debt": "Debt",
    "edit": "Edit",
    "add_to_my_home": "Add to My Home",
    "change_name": "Name",
    "delete_template": "Delete template",
    "delete_template_confirm": "Do you want to delete template",
    "payment_went_successfully": "Payment Completed Successfully",
    "add_template": "Add Template",
    "create_new_template": "Create New Template",
    "choose_template": "Choose Template",
    "add": "Add",
    "payment_completed_successfully": "Payment Completed Successfully",
    "receiver": "Receiver",
    "payed_amount": "Payed Amount",
    "templates_could_not_be_payed": "{{count}}Templates could not be Payed",
    "saving": "Saving",
    "offers_and_applications": "Offers and Applications",
    "clear_data": "Clear Data",
    "logout": "Logout",
    "remove_faceid_confirm": "Do you want to remove faceID",
    "disable": "Disable",
    "profile": "Profile",
    "change_password": "Password",
    "change_cover": "Cover",
    "manage_accounts": "Manage Accounts",
    "manage_notifications": "Manage Notifications",
    "authorization_method": "Authorization Methods",
    "ka": "Ka",
    "ka-mg": "Ka MG",
    "ka-sv": "Ka SV",
    "en": "En",
    "ru": "Ru",
    "lastname": "Lastname",
    "add_email": "Email",
    "email": "Email",
    "accept_to_share_photo": "Accept to share photo public",
    "confirm_unsaved_profile_description": "Do you want leave page unsaved profile",
    "old_password": "Old Password",
    "new_password": "New Password",
    "customer_id": "Customer Id",
    "check": "Check",
    "extra": "Extra",
    "addres": "Addres",
    "description": "Description",
    "fee": "Fee",
    "penalty": "Penalty",
    "merchant_name": "Merchant Name",
    "create_template": "Template",
    "choose_category": "Select Category",
    "service": "Service",
    "jer": "times",
    "change_cover_confirm": "Do you want to change cover",
    "change": "Change",
    "account_or_id_or_number": "IBAN, ID or Mobile",
    "currencies": "Currencies",
    "service_price": "Service price",
    "file_download_success": "File download completed successfully",
    "you_dont_have_fav_contacts": "You don't have favorite contacts",
    "abonent_number": "Cusromer Number",
    "abonent_number": "Customer Number",
    "template_name": "Template Name",
    "income2": "Income",
    "expenses": "Expenses",
    "other": "Other",
    "ads": "Ads",
    "from_choose_account": "From Choose Account",
    "personal_transfer": "Personal Transfer",
    "transfer_went_successfully": "Transfer was Successfully",
    "current_account": "Current Account",
    "card_account": "Card Account",
    "loan": "Loan",
    "payment_date": "Payment Date",
    "next_payment_date": "Next Payment Date",
    "next_payment_amount": "Next Payment Amount",
    "loan_value_date": "Loan Disbursement Date",
    "loan_end_date": "Loan End Date",
    "loan_related_account": "Loan Related Account",
    "ongoing_payment": "Payment",
    "no_contacts": "No contacts yet, press button to sync",
    "import_contacts": "Import Contacts",
    "in_days": "In {{n}} days",
    "cmts_transfers": "Remitances",
    "cmts_transfer": "Remitance",
    "sender": "Sender",
    "sender_country": "Sender country",
    "receive_transfer": "Receive remitance",
    "transfer_code": "Remitance code",
    "cmts_received_successfully": "Remitance request is in progress",
    "convertion_went_successfully": "Convertion completed succesfully",
    "no_result": "Result not found",
    "contact_not_found": "Contact not found",
    "auth_methods": "Authorization methods",
    "turn_on_faceid": "Turn on Face ID",
    "turn_on_faceid_desc": "Sign in with {{local_auth_method}} or Passcode",
    "turn_on_passcode": "Turn on Passcode",
    "turn_on_passcode_desc": "Sign in with Passcode",
    "transactions_not_found": "Transactions not found",
    "with_transaction_type": "Transaction type",
    "with_account": "Account number",
    "with_card": "Card number",
    "WRONG_LOGIN": "Wrong log in",
    "GENERAL_ERROR": "Error occurred",
    "BAD_REQUEST": "Error occurred",
    "SERVICE_CALL_ERROR": "Error occurred",
    "NOT_FOUND": "Not found",
    "UNAUTHORIZED": "Please sign in",
    "ALREADY_EXISTS": "Already exists",
    "CUSTOMER_ALREADY_EXISTS": "Invalid user",
    "USERNAME_ALREADY_EXISTS": "User already exists",
    "WRONG_INPUT_INFO": "Incorrect data",
    "INCORRECT_OLD_PASSWORD": "Old password is incorrect",
    "CANNOT_ADD_LOCAL_ACCOUNT": "Source and target account is same",
    "INSUFFICIENT_FUNDS": "You don't have sufficient funds",
    "INSUFFICIENTFUNDS": "You don't have sufficient funds",
    "InsufficientFunds": "You don't have sufficient funds",
    "LOAN_REJECTED": "The application is rejected",
    "STUDENT_LOAN_INVALID_IMAGES": "Invalid Images",
    "FILL_REQUIRED_FIELDS": "Please fill in all fields",
    "INVALID_PERSONAL_NUMBER": "ID number is incorrect",
    "INVALID_MOBILE_NUMBER": "Phone number is incorrect",
    "INVALID_GUARANTOR_BIRTH_DATE": "Wrong date of birth",
    "INVALID_GRACE_PERIOD": "Wrong grace period",
    "INVALID_YEAR": "Data is incorrect",
    "IMAGE_SIZE": "File size exceeded",
    "USER_IS_BLOCKED": "User is blocked",
    "CALCULATE_FEE_ERROR": "Error during the fee calculation",
    "INVALID_VALUE": "Data is incorrect",
    "CHECK_CUSTOMER_IN_CREDIT_INFO_FAILED": "Operation cannot be completed. Please, try again later",
    "SEND_LOAN_APPLICATION_NOT_ALLOWED": "Your application requires identification. Unfortunately, we cannot serve you at this moment",
    "403": "Error occurred",
    "ACCOUNT_NOT_BELONG_TO_CUSTOMER": "Account does not match to user",
    "LOAN_IS_NOT_APPROVED": "Loan is not approved",
    "LOAN_IS_ALREADY_ISSUED": "Loan is already active",
    "LOAN_NEEDS_AUTHORIZATION": "Please sign in",
    "LOAN_HAS_NOT_CONTRACT": "Loan contract does not exists",
    "LOAN_REGISTRATION_FAILED": "Loan registration cannot be performed",
    "LOAN_BIND_ACCOUNT_FAILED": "Eror accurred",
    "LOAN_GENERATE_SCHEDULE_FAILED": "Error occurred",
    "LOAN_LOAD_FAILED": "Loan was not loaded",
    "LOAN_GENERATE_CONTRACT_FAILED": "Error occurred",
    "WRONG_PERSONAL_NUMBER": "ID number is incorrect",
    "WRONG_PERSON_NAME_SURNAME": "Wrong name",
    "INVALID_USERNAME_CHARACTERS": "Wrong symbols",
    "REQUEST_IS_EMPTY": "Error occurred",
    "SEND_LOAN_APPLICATION_NOT_ALLOWED_TODAY": "Your application is already submitted, please wait for the decision",
    "Commission_Not_Found": "Error accurred",
    "CUSTOMER_NEGATIVE_STATUS": "Requested loan is not approved. Please, fill the new application on the below address",
    "InternalError": "Error occurred",
    "INTERNALERROR": "Error occurred",
    "CUSTOMER_NEEDS_AUTHENTIFICATION": "Identification is necessary for the application submission",
    "CMTS_AMOUNT_FAILED": "Amoint must not exceed 10 000 Gel",
    "CMTS_DAYLY_COUNT_FAILED": "Only 5 requests are allowed in 24 hours",
    "YOUR_USERNAME_IS_BLOCKED": "User is blocked",
    "AccountAndBankIsDifferent": "Account number is different",
    "ACCOUNTNOTBELONGSTOPERSON": "Account holder is different",
    "AccountNotBelongsToPerson": "Account holder is different",
    "CMTS_CURRENCY_FAILED_PT1": "If your remitance is not in Gel",
    "CMTS_CURRENCY_FAILED_PT2": "Please select same currency",
    "FORMAT": "Wrong format",
    "CMTS_NOT_FOUND": "Remitance not found",
    "RECEIVERACCOUNTNOTFOUND": "Receiver account not found",
    "CUSTOMER_RED_STATUS": "Your application is rejected",
    "INSERTONLYALLOWEDCHARACTERS": "Please enter valid symbols",
    "INVALID_CHARACTERS_NAME_ON_CARD": "Invalid symbols in card holder name fields",
    "CARD_APP_EXISTS": "There is an existing card application",
    "WRONG_OTP_CODE": "Otp is incorrect",
    "404_ERROR_CODE": "Error occurred, please try later",
    "INVALID_LOGIN": "Username is incorrect",
    "INVALID_PASSWORD": "Password is incorrect",
    "CARDHOLDER_NAME_VALIDITY": "*The number of characters exceed the allowable limit. In case of editing, please use the first letter of the name and the surname - in full. Use the missing space between the name and surname name. Otherwise, the card will not be ordered",
    "INVALID_USERNAME_LENGTH": "Please enter at least 3 symbols",
    "GENERATE_OTP_FAILED": "Error occurred",
    "USA_NOT_CONFIRMED_CITIZEN": "Customer infomation is not valid please call to bank",
    "CSS_CALL_ERROR": "Error occurred",
    "INCOMPLETE_CLIENT_DATA": "Registration is not possible",
    "RECEIVER_PERSON_IS_EMPTY": "Reviever person name is empty",
    "USERNAME_NOT_FOUND": "User name not found",
    "NOT_BLOCKED": "User is not blocked",
    "OUT_OF_TRIES": "You have already reached maximum limit of tries, please use password recovery",
    "ACCOUNT_NOT_FOUND": "Account not found",
    "INVALID_DATE_RANGE": "Please select corect range of date",
    "PERSON_NOT_FOUND": "Customer not found",
    "PERSON_IS_NOT_CLIENT": "You are not registered in bank",
    "ACCOUNT_PERSON_MISMATCH": "Account does not match to user",
    "ACCOUNT_ALREADY_DEFAULT": "Default account is already selected",
    "MOBILE_ALREADY_IN_USE_BY_CREDO_BANK_CUSTOMER": "Mobile number is already used",
    "PASSWORD_MISMATCH": "Password is incorect",
    "EMPTY_MOBILE": "Please enter mobile number",
    "EMPTY_PERSONAL_N": "Please enter personal number",
    "INCORRECT_PERSONAL_N": "ID number is incorrect",
    "EMPTY_BIRTH_DATE": "Please enter date of birth",
    "NOT_TRUSTED": "Error occurred",
    "INVALID_CONTRACT_NUMBER": "Wrong contract number",
    "CHOOSE_DRAFT_APPLICATION": "Select application",
    "INVALID_CURRENCY": "Wrong currency",
    "CHOOSE_CURRENCY": "Select Currency",
    "CHOOSE_ACCOUNT": "Select Account",
    "REQUIRED": "Mandatory fields are empty",
    "INVALID_ACCESS": "Invalid access",
    "VALIDATION_FAIL": "Incorrect data",
    "CMTS_CURRENCY_FAILED": "Incorect currency",
    "RESTORE_PASSWORD_FAILED": "Error occurred",
    "FILE_SIZE_EXCEED": "File size exceeded",
    "INVALID_PAGING_PARAMS": "The page cannot be found",
    "CONTACT_ALREADY_EXIST": "Contact already exists",
    "ABONENT_NOT_FOUND": "Customer not found",
    "premium": "Premium",
    "utility_payment": "Utility Payment",
    "sender_name": "Account name",
    "app_version": "App Version: {{version}}",
    "click_to_upload_photo": "Press to change picture",
    "show_todays_expenses_on_homepage": "show daily costs on homepage",
    "password_change_success": "Password changed successfully",
    "eur": "EUR",
    "clear_data_confirm": "Are you sure to clear data",
    "choose_image_upload_source": "Select image",
    "choose_from_gallery": "Select from gallery",
    "take_a_picture": "Take a picture",
    "cmts_info": "Please wait notification",
    "account_already_exists": "Contact already exists",
    "5.3.3.1": "Error occurred",
    "UTILITY_GET_DEBT_ERROR": "Error accurred",
    "turn_on_fingerprint": "Turn on Fingerprint",
    "turn_on_touch_id": "Turn on Touch ID",
    "rename_success": "Renamed successfully",
    "convert": "Convert",
    "unblock_card": "Unblock card",
    "unblock_card_confirm": "Confirm to unblock",
    "convert_desc": "Convert amount",
    "other_payments": "Other payment",
    "parking": "Parking and fines",
    "gov_services": "Public services",
    "fun": "Entertainment",
    "delivery": "Parcels",
    "education": "Education",
    "finances": "Financial services",
    "continue_with_id": "Continue with ID card",
    "continue_with_passport": "Continue with passport",
    "for_registration_you_need": "For registration is need",
    "id_card_or_passport": "ID card or passport",
    "good_lighting": "Good lighting",
    "connected_to_wifi": "Connected to Wifi",
    "registration_time": "2 minutes",
    "no": "No",
    "yes": "Yes",
    "choose_status": "Indicate Entrepreneurial Status",
    "selfie_instructions": "Make sure you take the selfie in good light, your hair does not cover your face, you do not have glasses on and your eyes are not closed",
    "individual_entity": "Physical person",
    "entrepreneur": "Entrepreneur",
    "entrepreneur_status": "Entrepreneurial status",
    "rsge_registration_date": "Date of registration on RS.ge",
    "reason_for_account": "Account Purpose",
    "expected_income": "Expected annual flow in Credo bank",
    "employment_status": "Employee Status",
    "income_source": "Income source",
    "enter_income_source": "Enter the source of income",
    "monthly_income": "Monthly income",
    "marriage_status": "Marital status",
    "official_address": "Official address",
    "current_address": "Current address",
    "profession": "Profession",
    "position": "Position",
    "citizen_of_usa": "I have USA citizenship",
    "was_born_in_usa": "I was born in USA",
    "have_green_card": "Green card owner",
    "have_parallel_citizenship": "I have dual citizenship of America and Georgia",
    "BANK_OF_USA_ERROR": "You are associated with the US tax system. Please visit the nearest Credo Bank service center to complete the process of signing and registering for additional documentation.",
    "check_ent_status": "To check your entrepreneurial status and other data, please visit to the link",
    "politically_active": "Are you politically active?",
    "processing": "Processing",
    "filled_applications": "Applications",
    "request_new_product": "Request new product",
    "you_dont_have_filled_application": "You don’t have filled application",
    "request_new_card": "Request new card",
    "request_card_description": "Request new card and we will deliver",
    "request_loan_description": "Request new loan",
    "request_account_description": "open new account or add new currency",
    "request_deposit_description": "Request new deposit",
    "choose_card_type": "Choose card type",
    "enter_card_name": "Name on card",
    "or_attach_existing_account": "Attach account",
    "delivery_service": "Card delivery",
    "take_from_branch": "Take from branch",
    "card_delivery_options_desc": "How you want take a card",
    "enter_address": "Type adress",
    "choose_branch": "Select branch",
    "choose_county": "Select country",
    "loan_details": "Loan details",
    "loan_amount": "Loan amount",
    "duration": "Duration",
    "effective_rate": "Effective interest rate",
    "create_new_account": "Create new account",
    "open_new_account": "Open new account",
    "open_account": "Open account",
    "request_account": "Request account",
    "price": "Price",
    "free": "Free",
    "request_deposit": "Request deposit",
    "deposit_details": "Deposit details",
    "deposit_name": "Deposit name",
    "deposit_type": "Deposit type",
    "deposit_duration": "Deposit duration",
    "request_account_success": "Request account went successfully",
    "request_loan_success": "Loan request went successfully",
    "attach_new_account": "Attach new account",
    "request_card_success": "Card request account went successfully",
    "download_agreement": "Download agreement",
    "in_process": "in progress",
    "issued": "Disbursed",
    "repeat": "Repeat",
    "CRA_PHOTO_MISMATCH": "Selfie does not match with the photo existing in Public Service Development Agency",
    "EXPIRED_DOC": "The document uploaded by you is expired",
    "INVALID_DOCUMENT_TYPE": "Please use an ID card or Passport while registering",
    "DOC_NOT_FOUND": "The document could not be found in Public Service Development Agency",
    "ADDRESS_CITY_MISMATCH": "City could not be found. Please re-enter the address",
    "AML_BLOCKED": "Your request requires additional information, please visit Credo Bank Service Center to complete the registration process",
    "NEEDS_APPROVE": "Your request is being processed, please check your registration status later",
    "MYCREDO_REG_ERROR": "An error occurred while registering Mycredo, please contact Credo Bank on 0322 42 42 42",
    "CSS_REGISTRATION_ERROR": "Registration requires additional information, please visit Credo Bank Service Center to complete the process",
    "CREATE_ACCOUNT_ERROR": "Account opening proccess has been delayed, please try to register again or visit Credo Bank to complete the process",
    "PERSON_NOT_ADULT": "Age Restriction - the specified age is below 18 years",
    "FACE_RECOGNITION_FAILED": "Please try to register again in a better lit environment and make sure nothing covers your face",
    "INVALID_ENTERPREUNEUER_DATA": "To register as an entrepreneur, you need to fill in all the required fields",
    "TRANSFER_LIMIT_1000": "Transfer of more than 10000 GEL is currently unavailable, please contact Credo Service Center",
    "INITIAL_DATA_ERROR": "Please check the information provided is correct (personal number/date of birth)",
    "DOCUMENT_FACE_MISMATCH": "The photo taken is different from the photo in the database of the Public Service Development Agency. To complete the registration process, please visit the nearest Credo Bank service center.",
    "DOCUMENT_READ_ERROR": "The document is not valid. Please try again using a valid document",
    "treasury": "Exchequer",
    "treasury_code": "Exchequer code",
    "treasury_name": "Name",
    "auth_for_product": "To order the product, please complete registration or visit the service center To open an account, please complete registration or visit the service center",
    "agree_to_not_entrepreneur": "I confirm, that: a) I do not represent a physical person, hence the current account, opened through the electronic application, will not be used for entrepreneurial purposes; b) I will be responsible for all the consequences of violating this condition. \n",
    "acc_type_7001": "JointAccount",
    "acc_type_6000": "Technical",
    "acc_type_6004": "Saving Account",
    "acc_type_1002": "Business overdraft",
    "acc_type_1001": "CurrentAccount",
    "acc_type_6005": "CurrentAccount",
    "PULSAR_UNEXPECTED_ERROR": "General error. Please contact the bank",
    "TRANSFER_LIMIT_10000": "Transfer limit - 10000 GEL. Please try again.",
    "ONBOARDING_LIMIT": "Registration is unavailable, contact the bank",
    "ONBOARDING_OTP_LIMIT": "Sms code is invalid",
    "DOC_FRONT_BACK_MISMATCH": "The document is not valid. Please try again using a valid document.",
    "gracePeriodMonthlyPayment": "Monthly payment during the period of grace",
    "loan_limits_text": "Loan with a term of 5000 GEL or more than 24 months only for persons engaged in agricultural activities",
    "percent_rate": "Percentage rate",
    "standart": "Standard",
    "emigrant": "Emigrant's",
    "card_receiver": "Please indicate the name, surname and personal\nnumber of the person who will receive the card",
    "not_enough_money_for_card": "There is not enough money in your account to order a card",
    "month": "Month(s)",
    "i_agree_conditions": "I agree to the terms",
    "request_deposit_success": "The deposit request has been sent successfully",
    "you_must_agree_condition": "Please agree to the terms",
    "conditions": "To the terms",
    "card_type": "Card type",
    "not_enough_money": "Insufficient amount on the current account, to cover the delivery price of the card (GEL {{cardCommissionFee}}). Please, place the amount on the account",
    "emigrant_card": "Immigrant Card",
    "standart_card": "Standard card",
    "cardstatus_1": "New",
    "cardstatus_3": "To be activated",
    "loan_amount_limits_desc": "Loan size - min GEL 3 000, max - GEL 10 000",
    "loan_duration_limits_desc": "Loan term - min 7 months, max - 36 months",
    "amount_min_error": "Minimum amount shall be {{x}}",
    "amount_max_error": "Maximum amount shall be {{x}}",
    "0": "Terms and conditions",
    "agreement_1": "By signing this application, I agree, that JSC Credo Bank processes my personal data, in compliance with Georgian law on Personal Data Protection. In particular, JSC Credo Bank is authorized to: A) periodically transfer my personal data to any third party (including the commercial banks operating in Georgia, Public Service Development Agency and its subsidiaries, etc.) for the purpose of analyzing my repayment capacity and/or offering any type of banking product and service (including the non-credit products and services). B) retrieve my personal data preserved by any third party, for the purpose set out in subparagraph (A) above. \n \n",
    "agreement_2": "JSC Credo Bank \n \nConsent on the retrieval of information about income from the Revenue Service\n \nCustomer name, surname: {{name}} \n \nI, {{name}} (ID Number {{personalN}}) agree, that JSC Credo Bank retrieves my personal information from Revenue Service, in order to apprise my repayment capacity. In case of need, JSC Credo Bank shall also enforce the registration of my communication via the electronic form of Revenue Service \n \nDate: {{date}}",
    "agreement_3": "The customer agrees and authorizes JSC Credo Bank (hereinafter referred to as the Bank) to collect/process the Customer information, including biometric data, as well as the information stored in the electronic database of Public Service Development agency. The latter shall serve for the purpose of analyzing the repayment capacity, subsequently - to make a relevant offer of any type of banking products and services (including credit, deposit, etcAt the request of the customer (referred also as the subject of the data), the data processor is obliged to correct, update, add, block, delete or destroy data, if this data is incomplete, inaccurate, not updated, or in case it was collected and processed against the law",
    "agreement_4": "I, {{name}} express my consent and authorize \n JSC Credo Bank, in accordance with the Georgian legislation and applicable laws to process the information preserved by creditor and credit bureaus and the information provided by these entities for the purpose of analyzing my repayment capacity, as a borrower, co-borrower/ guarantor / security provider. \nI acknowledge the right under Georgian legislation, that as per the borrower’s (the data subject) request, data processor is obliged to correct, update, add, block, erase and destroy the data in case the data is incomplete, inaccurate, out-of-date, or if the data is collected and processed against the law. \n nThis consent is one-time and is valid for 30 working days after signing (for 60 working days in case of a legal entity). \n Name, surname of the applicant and personal number: \n {{name}} {N personalN}} \n Date: {{date}}",
    "agreement_5": "I {{name}} express my consent and authorize JSC Credo Bank, to obtain and process information from the database of the Ministry of Internal Affairs of Georgia, via JSC Creditinfo Georgia” (204470740). The purpose of my consent is to authorize Credo Bank to analyze and apprise my repayment capacity via checking the administrative offences to individual and legal entities and/or unfulfilled financial liabilities (administrative offence and/or fines or penalty interests). I acknowledge, that in accordance with the law, the Ministry of Internal Affairs of Georgia is obliged to correct, update, add, block, erase or destroy data in case the data is incomplete, inaccurate, out-of date, or if the data is collected and processed against the law.",
    "fill_pn_and_birthday": "Please, fill in ID and birth date fields",
    "rejected": "Rejected",
    "canceled": "Canceled.",
    "add_other_card": "Add other bank card",
    "add_card": "Add the card",
    "which_bank_card": "Which bank card?",
    "card_name": "Card name",
    "SESSION_NOT_FOUND": "An error has occurred",
    "OPERATION_VALIDATION_FAILED": "Entered data is incorrect",
    "INVALID_INPUT_DATA": "Data indicated is not correct",
    "trusted_devices": "Trusted devices",
    "trusted_devices_desc": "Mark your device as a \trusted device and you will enjoy the mobile banking services without specifying the SMS code",
    "this_device": "Current device",
    "user_unblock_instructions": "Please contact to the call center to unblock your account. Account will be unblocked automatically in 24 hours.",
    "OPERATION_USER_LOCKED": "The user has been blocked due to incorrect attempts.\n unblock is possible: \n1.button data recovery\\n2.via call center\n3.automatically on the next calendar day.\n",
    "OPERATION_CHALLENGE_TIMEOUT": "The code has expired",
    "add_contact_suggestion": "Add the contact as a \trusted beneficiary and after 24 hours, transfer operation can be proceed without SMS code",
    "simple_login_trusted_device": "Activate simple login and your device will be added as a \trusted device. You can enjoy mobile bank services without SMS code",
    "trusted_device": "Trusted Device",
    "passcode_auth": "Confirm action using passcode",
    "remove_contact_suggestion": "In case of cancellation of a trusted beneficiary, to confirm money operation you will need SMS code / fingerprint / Face ID or passcode",
    "end_date": "Ending time",
    "product_type": "Product type",
    "deposit": "Deposit",
    "of_loan": "Loan's",
    "to_schedule": "Graphic",
    "to_agreement": "Agreement",
    "pay_monthly": "Monthly payment",
    "period": "Period",
    "agreement": "Agreement",
    "download_contract": "Download the agreement",
    "activate_card_desc": "By clicking on the 'Confirm' button, you confirm that you have received the card and the PIN code of the card will be sent to your phone number",
    "activate_card": "Card activation",
    "activate_card_pin": "Please, enter the last 4 digits of the card",
    "activate_card_success": "Your card has been successfully activated",
    "retry": "Retry",
    "instalment": "Installment",
    "of_instalment": "Installment's",
    "do_you_have_promo": "Do you have the promo code?",
    "promo_code": "Promo code",
    "referer": "Inviter",
    "your_promo_code": "Your promo code",
    "promo_copied_successfully": "Promo code is successfully copied",
    "add_to_deposit": "Deposit top up",
    "NEW": "New",
    "READY_FOR_RECEIVE": "Ready",
    "RECEIVING": "Admission is underway",
    "RECEIVED": "Received",
    "READY_FOR_SEND": "Prepared",
    "SENDING": "Sending",
    "SENT": "Sent",
    "ERROR": "An error has occurred",
    "ERROR_IN_CMTS": "Error has been occurred in remittance system",
    "ERROR_WRONG_AMOUNT": "Error has been occurred, insufficient amount",
    "ERROR_WRONG_CURRENCY": "Error has been occurred, wrong currency",
    "ERROR_SYSTEM_ERROR": "System error",
    "ERROR_GO_TO_BRANCH": "Error has been occurred, please contact the Bank",
    "ERROR_BLOCKED_CALL_SENDER": "Error has been occurred, please contact the Bank",
    "IN_PROCESS": "in progress",
    "cmts_KORONA": "ЗОЛОТАЯ КОРОНА",
    "cmts_RIA": "RIA",
    "cmts_INTEL_EXPRESS": "IntelExpress",
    "cmts_MONEY_GRAMM": "MoneyGram",
    "cmts_UNISTREAM": "Unistream",
    "cmts_CONTACT": "Contact",
    "cmts_SPRINT": "Sprint",
    "cmts_WESTER_UNION": "Western Union",
    "DEPOSIT_SAME_ACC": "Please select a serving account for deposit",
    "INVALID_ACCOUNT": "Please select a serving account for deposit",
    "EXISTING_STATE_NEW": "We inform you, that the specified code has already been used for money transfer. Remittance status - New",
    "EXISTING_STATE_READY_FOR_RECEIVE": "We inform you, that the specified code has already been used for money transfer. Remittance status - Ready for receive",
    "EXISTING_STATE_RECEIVING": "We inform you, that the specified code has already been used for money transfer. Remittance status - Receiving",
    "EXISTING_STATE_RECEIVED": "We inform you, that the specified code has already been used for money transfer. Remittance status - Received",
    "EXISTING_STATE_READY_FOR_SEND": "We inform you, that the specified code has already been used for money transfer. Remittance status - Ready for SEND",
    "EXISTING_STATE_SENDING": "We inform you, that the specified code has already been used for money transfer. Remittance status - Sending",
    "EXISTING_STATE_SENT": "We inform you, that the specified code has already been used for money transfer. Remittance status - Sent",
    "EXISTING_STATE_ERROR": "We inform you, that the specified code has already been used for money transfer. Remittance status - error has been occured",
    "EXISTING_STATE_ERROR_IN_CMTS": "We inform you, that the specified code has already been used for money transfer. Remittance status - error has been occurred in remittance system",
    "EXISTING_STATE_ERROR_WRONG_AMOUNT": "We inform you, that the specified code has already been used for money transfer. Remittance status - error has been occurred - wrong amount",
    "EXISTING_STATE_ERROR_WRONG_CURRENCY": "We inform you, that the specified code has already been used for money transfer. Remittance status - error has been occurred - wrong currency",
    "EXISTING_STATE_ERROR_SYSTEM_ERROR": "We inform you, that the specified code has already been used for money transfer. Remittance status - system error has been occurred",
    "EXISTING_STATE_ERROR_GO_TO_BRANCH": "We inform you, that the specified code has already been used for money transfer. Remittance status - system error has been occurred",
    "EXISTING_STATE_ERROR_BLOCKED_CALL_SENDER": "We inform you, that the specified code has already been used for money transfer. Remittance status - error has been occurred - please contact the Bank",
    "EXISTING_STATE_IN_PROCESS": "We inform you, that the specified code has already been used for money transfer. Remittance status - processing",
    "EXISTING_STATE_NOT_FOUND": "We inform you, that the specified code has already been used for money transfer. Remittance status - remittance cannot be found",
    "learn_more": "Learn More",
    "GEL": "GEL",
    "USD": "USD",
    "EUR": "EUR",
    "RUB": "RUB",
    "GBP": "GBP",
    "deferredInterest": "Deferred interest rate",
    "credit_cards": "Credit and installment cards",
    "deposit_widget_h": "Deposits in Credo Bank",
    "loan_widget_h": "Apply for and get a loan online",
    "card_widget_h": "Plastic Cards",
    "online_contract_success": "Loan request completed successfully",
    "activate_simple_login_and_make_transactions": "Activate simple login and complete transactions without OTP code",
    "utility_widget_d": "Pay bills without commission!",
    "utility_widget_h": "Free Bills",
    "account_widget_h": "Open an account in desired currency",
    "deposit_widget_d": "Open the desired type of deposit, get high interest rates!",
    "loan_widget_d": "Based on any kind of income!",
    "card_widget_d": "Order and get to desired address for free!",
    "account_widget_d": "Perform banking operations easily!",
    "add_currency": "Add currency",
    "request_currency_success": "Currency has been successfully added",
    "annual_interest_with_cash": "Annual % on the withdrawn limit",
    "annual_interest_with_payments": "Annual % on the absorbed limit via payments",
    "credit_limit": "Credit limit",
    "available_amount": "Available amount",
    "date_calculation": "Calculation date",
    "LimitUsedCalculationDate": "Applied limit on the calculation date",
    "BasicAmount": "Principal",
    "AccruedInterest": "Accrued interest",
    "MinimumFee": "Minimum amount payable",
    "PaymentDate": "Payment date",
    "fulfill_limit": "Limit top up",
    "fx_limit_calculator": "If the indicated amount exceeds the daily limit - 20000, please apply the standard conversion rate for the remaining amount",
    "fx_limit": "The indicated amount exceeds daily limit - 20000, please apply the standard conversion rate on for the remaining amount",
    "which_products_do_you_use": "Which Credo Bank products do you use?",
    "finance_operations": "Financial operations",
    "messages": "Notifications",
    "previous": "Previous",
    "new_message": "New notification",
    "title": "Headline",
    "description_label": "Description",
    "send_message": "Send the notification",
    "delete_message_confirm": "Are you sure you want to erase the notification?",
    "message": "Notification",
    "mark_as_unread": "Mark unread",
    "inbox": "Received",
    "outbox": "Sent",
    "message_sent_successfully": "Message has been successfully sent",
    "loan_amount_questions": "Loan amount",
    "instalment_amount": "Installment amount",
    "last_amount": "Amount paid last time",
    "deposit_amount": "Deposit initial amount",
    "deposit_last_date": "Deposit closure date",
    "deposit_start_date": "Deposit opening date",
    "q_income": "The latest incoming operation",
    "q_transfer": "The latest outgoing operation",
    "q_buy": "Online or POS terminal payment",
    "q_withdraw": "Money withdrawal from ATM",
    "how_much_LOAN_AMOUNT": "What is your loan amount",
    "how_much_INSTALLMENT_AMOUNT": "What is your installment amount?",
    "how_much_DEPOSIT_AMOUNT": "What is the initial amount of your deposit?",
    "how_much_LOAN_LAST_PAYMENT_AMOUNT": "What is the latest outgoing operation amount?",
    "how_much_INSTALLMENT_LAST_PAYMENT_AMOUNT": "What is the latest outgoing operation amount?",
    "how_much_FINANCIAL_OPERATION_CREDIT_AMOUNT": "Please, indicate the latest outgoing operation amount",
    "how_much_FINANCIAL_OPERATION_DEBIT_AMOUNT": "Please, indicate the latest incoming operation amount",
    "how_much_FINANCIAL_OPERATION_WITHDRAW_AMOUNT": "Please, indicate the latest cash withdrawal amount from ATM",
    "how_much_FINANCIAL_OPERATION_PURCHASE_AMOUNT": "Please, indicate the latest amount paid online or via POS terminal",
    "how_much_DEPOSIT_START": "What is your deposit opening date (month/year)?",
    "how_much_DEPOSIT_END": "What is your deposit closure date (month/year)?",
    "how_much_LOAN_NEXT_PAYMENT_DATE": "What is your loan repayment date (day/month)?",
    "how_much_INSTALLMENT_NEXT_PAYMENT_DATE": "What is your loan installment repayment date (day/month)?",
    "date": "Date",
    "next_payment": "Next repayment date",
    "your_username_is": "Your username is",
    "update_app": "Please, update the application",
    "update_app_desc": "Please, update the application in order to use the new functionality",
    "update": "Update",
    "OVERALL_SIZE_EXCEED": "Attached file exceeds the permitted size",
    "UNKNOWN_FILE_EXT": "Attached file format is not acceptable",
    "ATTACHEMENT_COUNT_EXCEED": "The number of attachements exceeds the acceptable level",
    "message_deleted_success": "Message was successfully deleted",
    "max_5_files_allowed": "Maximum 5 attachments are acceptable",
    "emigrant_card_commission_fee": "The delivery price of a card for emigrants is GEL {{cardCommissionFeeGeo}}, and in foreign countries - GEL {{cardCommissionFeeNotGeo}}. Please have a sufficient amount on your current account"
}
